== 功能列表

=== 通用模块

==== 接口统一返回数据结构

[source,java]
----
package cn.hiboot.mcn.core.model.result;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

@JsonInclude(JsonInclude.Include.NON_NULL)//Null字段不返回
public class RestResp<T> {

    public enum ActionStatusMethod {
        OK,
        FAIL
    }

    @JsonProperty("ActionStatus")//返回字段名大写,默认OK表示正常结果返回
	private ActionStatusMethod ActionStatus = ActionStatusMethod.OK;

    @JsonProperty("ErrorCode")//返回字段名大写,默认0表示无错误
	private Integer ErrorCode = 0;

    @JsonProperty("ErrorInfo")//返回字段名大写,错误具体信息(当异常返回时)
	private String ErrorInfo = "";

	@JsonProperty("Duration")//接口执行时间需结合注解@Timing使用
	private Long duration;

	private T data;//接口返回的数据

	private Long count;//数据返回的count数,分页时使用

    //省略set/get====
}
----

==== 常用工具类
* JacksonUtils(可在非spring环境中使用)
....
基于jackson的一个序列化和反序列化工具。

注意：当在SpringBoot项目里使用时,IOC容器中存在ObjectMapper则优先使用外部的
....

* SpringBeanUtils
....
方便在静态方法中从IOC容器获取bean的工具

注意：当存在多个上下文时且当前上下文是子上下文时会更新applicationContext
....

=== 扩展功能

==== 自定义bean装配注解@McnAutowired

当不想在项目中使用spring自动装配注解时使用(#一般使用不到#)

==== 内置属性源

系统内置五中属性源名称分别是：mcn-global-unique、mcn-default、mcn-map、mcn-log-file

* mcn-global-unique
....

只要EnvironmentPostProcessor触发就自动加载classpath:config/mcn.properties文件。即便该文件已加载！
注意：当启用了spring.profiles.active配置同时会加载文件mcn-{profile}.properties,当激活多个profile时且存在相同属性配置时后面的优先级比前面的高

....

* mcn-default

====
该属性源里包含很多配置如:

. server.tomcat.basedir=/tmp/tomcat/ #内嵌tomcat根路径
. server.compression.enabled=true #启用tomcat数据压缩

https://github.com/kse-music/mcn-boot-project/blob/master/mcn-boot-autoconfigure/src/main/java/cn/hiboot/mcn/autoconfigure/web/config/mcn-default.properties[查看所有配置]
====

* mcn-map
====
该属性源里只包含五个配置：

. app.base-package:项目启动的根路径即Application所在package
. logging.level.{app.base-package}.dao:设置dao包下的日志级别为info
. project.version:项目版本号读取manifest文件(如果存在)
. mcn.log.file.name:日志输出的文件名默认为error(注意：不包含扩展名)
. mcn.version:mcn版本号读取manifest文件
====

* mcn-log-file
....
该属性源里包含以下配置：

#日志文件所在路径,默认为/work/logs/${spring.application.name:none}/error.log
logging.file.name=${logging.file:${logging.baseDir:/work/logs}/${spring.application.name:none}/${mcn.log.file.name}.log}
#日志控制台输出格式
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %green(%-5level) %magenta(${PID:- }) --- [%15thread] %cyan(%-40logger{39}) %-5L : %msg%n
#日志文件输出格式
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level ${PID:- } --- [%15thread] %-40logger{39} %-5L : %msg%n
#日志配置文件
logging.config=classpath:META-INF/logback-spring.xml
#日志默认输出级别为info
logging.level.root=info
#org开头的包日志级别设为info
logging.level.org=warn
#io开头的包日志级别设为info
logging.level.io=warn
#CachingOperationNameGenerator类的日志级别设为warn
logging.level.springfox.documentation.spring.web.readers.operation.CachingOperationNameGenerator=warn
#日志文件保留最长时间30天
logging.logback.rollingpolicy.max-history=30
....

[WARNING]
====
  除了mcn-global-unique之外其它属性源默认不会加引导上下文中加载

. 当配置mcn.bootstrap.eagerLoad.enable=true可启用其它三个属性源也在引导上下文中加载

. 当环境中存在mcn-default属性源，则mcn-default、mcn-map、mcn-log-file属性源都不会加载

. 日志文件按天压缩，自动删除30天前日志
====

==== 打印属性源(#调试时使用,生产应关闭#)

当环境中存在mcn.print-env.enable=true时,项目在启动时会自动打印所有可枚举的属性源。

=== 自动配置

==== mybatis多数据源自动配置
由于目前推荐使用Jpa这里就不作介绍了

==== minio自动配置

====
扩展了MinioClient以实现分片直转minio服务器

https://github.com/kse-music/mcn-boot-project/blob/master/mcn-boot-autoconfigure/src/main/java/cn/hiboot/mcn/autoconfigure/minio/MinioProperties.java[查看配置]
====

==== 基于redis的分布式锁

====
使用方式两种:

. 使用注解@DistributedLock

. 编程使用DistributedLocker接口
====

==== xxl-job执行器自动配置

====

默认当classpath下存在XxlJobExecutor.class时自动配置

注意：可通过xxl.job.enable=false关闭自动配置
====

==== 统一异常处理
待补充

==== Swagger配置

. 默认swagger自动配置关闭 可通过swagger.enable=true开启

. 默认将带有注解RestController的接口生成文档忽略带有注解@IgnoreApi和@ApiIgnore的接口

==== 跨域配置

====
默认跨域不启动,可通过filter.cross=true启用跨域 方便开发调试

注意：生产环境一定要关闭跨域设置
====

==== WebSecurity扩展配置

====
当使用了SpringSecurity时自动忽略以下路径：

/v2/api-docs,/swagger-resources/**,/doc.html,/webjars/**,/error,/favicon.ico,/_imagePreview

注意：可通过web.security.enable-default-ignore=false关闭默认忽略，也可以通过web.security.exclude-urls=/a/b,/c/**添加更多放行路径
====

==== Validator配置

. 配置了hibernate.validator.fail_fast=true，当第一个参数校验失败后续不校验

. #扩展了分组校验区分校验时是否需要校验默认分组#

. 提供注解@Phone校验手机号

[WARNING]
====
@Phone 仅简单校验了11位数字手机号
====


=== 版本管理

. 除SpringBoot和SpringCloud管理以外的版本管理

.版本管理
[width="100%",options="header,footer"]
|====================
| Jar | Version
| guava | 31.0.1-jre
| mybatis-spring-boot-starter | 2.2.0
| commons-io | 2.11.0
| spring-boot-admin-starter-client | 2.5.2
| spring-boot-admin-starter-server | 2.5.2
| jsoup | 1.14.3
| fastjson | 1.2.78
| swagger | 1.6.1
| mapstruct | 1.4.2.Final
| minio | 8.3.3
| spring-cloud-alibaba | 2021.1
| xxl-job | 2.3.0
|====================

